## Unsupervised Learning Trading Strategy
- Download/Load SP500 stocks prices data.
- Calculate different features and indicators on each stock.
- Aggregate on monthly level and filter top 150 most liquid stocks.
- Calculate Monthly Returns for different time-horizons.
- Download Fama-French Factors and Calculate Rolling Factor Betas.
- For each month fit a K-Means Clustering Algorithm to group similar assets based on their features.
- For each month select assets based on the cluster and form a portfolio based on Efficient Frontier max sharpe ratio optimization.
- Visualize Portfolio returns and compare to SP500 returns.

## All Packages Needed:
- pandas, numpy, matplotlib, statsmodels, pandas_datareader, datetime, yfinance, sklearn, PyPortfolioOpt

In [1]:
%pip install pandas
%pip install numpy
%pip install matplotlib
%pip install statsmodels
%pip install pandas-datareader
%pip install datetime
%pip install yfinance
%pip install scikit-learn
%pip install PyPortfolioOpt
%pip install pandas_ta

Requirement already satisfied: pandas in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (2.1.3)
Requirement already satisfied: numpy<2,>=1.23.2 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas) (1.26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (1.26.2)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: matplotlib in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (3.8.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from matplotlib) (4.44.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy<2,>=1.21 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from matplotlib) (1.26.2)
Requirement already satisfied: packaging>=20.0 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=8 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from matplotlib) (10.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from matplotlib) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: statsmodels in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (0.14.0)
Requirement already satisfied: numpy>=1.18 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from statsmodels) (1.26.2)
Requirement already satisfied: scipy!=1.9.2,>=1.4 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from statsmodels) (1.11.4)
Requirement already satisfied: pandas>=1.0 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from statsmodels) (2.1.3)
Requirement already satisfied: patsy>=0.5.2 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from statsmodels) (0.5.3)
Requirement already satisfied: packaging>=21.3 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from statsmodels) (23.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas>=1.0->statsmodels) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas>=1.0->statsmodels) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas>=1.0->statsmodels) (2023.3)
Requirement already satisfied: six in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from patsy>=0.5.2->statsmodels) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas-datareader in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (0.10.0)
Requirement already satisfied: lxml in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas-datareader) (4.9.3)
Requirement already satisfied: pandas>=0.23 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas-datareader) (2.1.3)
Requirement already satisfied: requests>=2.19.0 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas-datareader) (2.31.0)
Requirement already satisfied: numpy<2,>=1.23.2 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas>=0.23->pandas-datareader) (1.26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas>=0.23->pandas-datareader) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas>=0.23->pandas-datareader) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas>=0.23->pandas-datareader) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from requests>=2.19.0->pandas-datareader) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from requests>=2.19.0->pandas-datareader) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from requests>=2.19.0->pandas-datareader) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from requests>=2.19.0->pandas-datareader) (2023.11.17)
Requirement already satisfied: six>=1.5 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas-datareader) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: datetime in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (5.3)
Requirement already satisfied: zope.interface in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from datetime) (6.1)
Requirement already satisfied: pytz in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from datetime) (2023.3.post1)
Requirement already satisfied: setuptools in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from zope.interface->datetime) (65.5.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: yfinance in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (0.2.32)
Requirement already satisfied: pandas>=1.3.0 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from yfinance) (2.1.3)
Requirement already satisfied: numpy>=1.16.5 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from yfinance) (1.26.2)
Requirement already satisfied: requests>=2.31 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from yfinance) (2.31.0)
Requirement already satisfied: multitasking>=0.0.7 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from yfinance) (4.9.3)
Requirement already satisfied: appdirs>=1.4.4 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from yfinance) (2023.3.post1)
Requirement already satisfied: frozendict>=2.3.4 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from yfinance) (2.3.8)
Requirement already satisfied: peewee>=3.16.2 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from yfinance) (3.17.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from yfinance) (4.12.2)
Requirement already satisfied: html5lib>=1.1 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: six>=1.9 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from requests>=2.31->yfinance) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from requests>=2.31->yfinance) (2023.11.17)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: scikit-learn in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (1.3.2)
Requirement already satisfied: numpy<2.0,>=1.17.3 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from scikit-learn) (1.26.2)
Requirement already satisfied: scipy>=1.5.0 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from scikit-learn) (3.2.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: PyPortfolioOpt in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (1.5.5)
Requirement already satisfied: cvxpy<2.0.0,>=1.1.19 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from PyPortfolioOpt) (1.4.1)
Requirement already satisfied: numpy<2.0.0,>=1.22.4 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from PyPortfolioOpt) (1.26.2)
Requirement already satisfied: pandas>=0.19 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from PyPortfolioOpt) (2.1.3)
Requirement already satisfied: scipy<2.0,>=1.3 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from PyPortfolioOpt) (1.11.4)
Requirement already satisfied: osqp>=0.6.2 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from cvxpy<2.0.0,>=1.1.19->PyPortfolioOpt) (0.6.3)
Requirement already satisfied: ecos>=2 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from cvxpy<2.0.0,>=1.1.19->PyPortfolioOpt) (2.0.12)
Requirement already satisfied: clarabel>=0.5.0 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from cvxpy<2.0.0,>=1.1.19->PyPortfolioOpt) (0.6.0)
Requirement already satisfied: scs>=3.0 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from cvxpy<2.0.0,>=1.1.19->PyPortfolioOpt) (3.2.4)
Requirement already satisfied: pybind11 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from cvxpy<2.0.0,>=1.1.19->PyPortfolioOpt) (2.11.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas>=0.19->PyPortfolioOpt) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas>=0.19->PyPortfolioOpt) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas>=0.19->PyPortfolioOpt) (2023.3)
Requirement already satisfied: qdldl in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from osqp>=0.6.2->cvxpy<2.0.0,>=1.1.19->PyPortfolioOpt) (0.1.7.post0)
Requirement already satisfied: six>=1.5 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=0.19->PyPortfolioOpt) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas_ta in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (0.3.14b0)
Requirement already satisfied: pandas in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas_ta) (2.1.3)
Requirement already satisfied: numpy<2,>=1.23.2 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas->pandas_ta) (1.26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas->pandas_ta) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas->pandas_ta) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from pandas->pandas_ta) (2023.3)
Requirement already satisfied: six>=1.5 in /Users/jason/Workspace/personal/algo-trade/venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas->pandas_ta) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

1. Download/Load SP500 stocks prices data:

In [1]:
from statsmodels.regression.rolling import RollingOLS
import pandas_datareader.data as web
import matplotlib.pyplot as plt
import statsmodels.api as sm
import pandas as pd
import numpy as np
import datetime as dt
import yfinance as yf
import pandas_ta
import warnings
warnings.filterwarnings('ignore')

sp500 = pd.read_html('https://en.wikipedia.org/wiki/List_of_S&P_500_companies')[0]

sp500['Symbol'] = sp500['Symbol'].str.replace('.', '-')

symbols_list = sp500['Symbol'].unique().tolist()

end_date = '2023-11-21'

start_date = pd.to_datetime(end_date) - pd.DateOffset(365*8)

df = yf.download(tickers=symbols_list, start=start_date, end=end_date).stack()

df.index.names = ['date', 'ticker']

df.columns = df.columns.str.lower()

df

[*********************100%%**********************]  503 of 503 completed

2 Failed downloads:
['SOLV', 'GEV']: Exception("%ticker%: Data doesn't exist for startDate = 1448254800, endDate = 1700542800")

                    adj close       close        high         low        open  \
date       ticker
2015-11-23 A        37.352898   40.029999   40.070000   39.139999   39.290001
           AAL      40.423813   42.299999   42.740002   41.810001   42.110001
           AAPL     26.765539   29.437500   29.932501   29.334999   29.817499
           ABBV     42.874161   61.150002   61.529999   60.840000   61.310001
           ABT      38.928970   45.439999   46.099998   45.259998   46.029999
...                       ...         ...         ...         ...         ...
2023-11-20 XYL      99.918571  100.209999  101.059998  100.059998  100.919998
           YUM     126.881851  128.119995  128.580002  127.300003  127.940002
           ZBH     112.065308  112.500000  112.650002  111.339996  111.620003
           ZBRA    220.539993  220.539993  221.779999  216.600006  218.839996
           ZTS     175.661575  176.059998  177.000000  173.899994  174.320007

                        volume
date       ticker
2015-11-23 A         6473400.0
           AAL       4166100.0
           AAPL    129930000.0
           ABBV      6405000.0
           ABT       4593800.0
...                        ...
2023-11-20 XYL       1147100.0
           YUM        915000.0
           ZBH       1345100.0
           ZBRA       330600.0
           ZTS       1056700.0

[989944 rows x 6 columns]

2. Calculate features and technical indicators for each stock.
   - Garman-Klass Volatility
   - RSI
   - Bollinger Bands
   - ATR
   - MACD
   - Dollar Volume

In [10]:
# df['garman_klass_vol'] = ((np.log(df['high'])-np.log(df['low']))**2)/2 - (2*np.log(2)-1)*((np.log(df['adj close'])-np.log(df['open']))*2)

# df['rsi'] = df.groupby(level=1)['adj close'].transform(lambda x: pandas_ta.rsi(close=x, length=20))

# df['bb_low'] = df.groupby(level=1)['adj close'].transform(lambda x: pandas_ta.bbands(close=np.log1p(x), length=20).iloc[:,0])

# df['bb_mid'] = df.groupby(level=1)['adj close'].transform(lambda x: pandas_ta.bbands(close=np.log1p(x), length=20).iloc[:,1])

# df['bb_high'] = df.groupby(level=1)['adj close'].transform(lambda x: pandas_ta.bbands(close=np.log1p(x), length=20).iloc[:,2])

# def compute_atr(stock_data):
#   atr = pandas_ta.atr(high=stock_data['high'],
#                       low=stock_data['low'],
#                       close=stock_data['close'],
#                       length=14)
#   return atr.sub(atr.mean()).div(atr.std())

# df['atr'] = df.groupby(level=1, group_keys=False).apply(compute_atr)

# def compute_macd(close):
#   macd = pandas_ta.macd(close=close, length=20).iloc[:,0]
#   return macd.sub(macd.mean()).div(macd.std())

# df['macd'] = df.groupby(level=1, group_keys=False)['adj close'].apply(compute_macd)

# df['dollar_volume'] = (df['adj close']*df['volume'])/1e6

df

                    adj close       close        high         low        open  \
date       ticker
2015-11-23 A        37.476856   40.029999   40.070000   39.139999   39.290001
           AAL      40.423813   42.299999   42.740002   41.810001   42.110001
           AAPL     26.799692   29.437500   29.932501   29.334999   29.817499
           ABBV     43.283794   61.150002   61.529999   60.840000   61.310001
           ABT      39.117035   45.439999   46.099998   45.259998   46.029999
...                       ...         ...         ...         ...         ...
2023-11-20 YUM     128.119995  128.119995  128.580002  127.300003  127.940002
           ZBH     112.500000  112.500000  112.650002  111.339996  111.620003
           ZBRA    220.539993  220.539993  221.779999  216.600006  218.839996
           ZION     35.779999   35.779999   36.169998   35.560001   36.169998
           ZTS     176.059998  176.059998  177.000000  173.899994  174.320007

                        volume  garman_klass_vol        rsi    bb_low  \
date       ticker
2015-11-23 A         6473400.0          0.036778        NaN       NaN
           AAL       4166100.0          0.031815        NaN       NaN
           AAPL    129930000.0          0.082642        NaN       NaN
           ABBV      6405000.0          0.269052        NaN       NaN
           ABT       4593800.0          0.125897        NaN       NaN
...                        ...               ...        ...       ...
2023-11-20 YUM        915000.0         -0.001036  59.441962  4.778174
           ZBH       1345100.0         -0.005999  56.139679  4.623112
           ZBRA       330600.0         -0.005699  51.588388  5.286738
           ZION      1589000.0          0.008520  57.703637  3.372132
           ZTS       1056700.0         -0.007517  56.890496  5.026941

                     bb_mid   bb_high       atr      macd  dollar_volume
date       ticker
2015-11-23 A            NaN       NaN       NaN       NaN     242.602681
           AAL          NaN       NaN       NaN       NaN     168.409647
           AAPL         NaN       NaN       NaN       NaN    3482.084002
           ABBV         NaN       NaN       NaN       NaN     277.232703
           ABT          NaN       NaN       NaN       NaN     179.695835
...                     ...       ...       ...       ...            ...
2023-11-20 YUM     4.828897  4.879620  0.199591  0.895190     117.229796
           ZBH     4.680042  4.736972 -0.254995  0.202355     151.323750
           ZBRA    5.345200  5.403662 -0.012923 -0.160356      72.910522
           ZION    3.515364  3.658596 -0.092737  0.696147      56.854418
           ZTS     5.115873  5.204804  0.963583  0.488186     186.042599

[994838 rows x 14 columns]

3. Aggregate to monthly level and filter top 150 most liquid stocks for each month.
   - To reduce training time and experiment with features and strategies, we convert the business-daily data to month-end frequency.

In [11]:
last_cols = [c for c in df.columns.unique(0) if c not in ['dollar_volume', 'volume', 'open', 'high', 'low', 'close']]

data = (pd.concat([df.unstack('ticker')['dollar_volume'].resample('M').mean().stack('ticker').to_frame('dollar_volume'),
           df.unstack()[last_cols].resample('M').last().stack('ticker')],
           axis=1)).dropna()

data

                   dollar_volume   adj close  garman_klass_vol        rsi  \
date       ticker
2015-12-31 A          103.333139   39.250362          0.050582  57.183845
           AAL        319.493892   40.471584          0.038663  47.951441
           AAPL      4258.527206   23.956997          0.085486  30.946553
           ABBV       294.510549   41.931831          0.270428  52.892381
           ABT        211.476896   38.660789          0.119282  48.262397
...                          ...         ...               ...        ...
2023-11-30 YUM        181.963715  128.119995         -0.001036  59.441962
           ZBH        239.748735  112.500000         -0.005999  56.139679
           ZBRA       106.252939  220.539993         -0.005699  51.588388
           ZION        71.560611   35.779999          0.008520  57.703637
           ZTS        438.153718  176.059998         -0.007517  56.890496

                     bb_low    bb_mid   bb_high       atr      macd
date       ticker
2015-12-31 A       3.644514  3.676936  3.709358 -1.161306  0.095303
           AAL     3.695287  3.743884  3.792481  0.607890  0.112604
           AAPL    3.194346  3.269361  3.344377 -1.002304 -0.730643
           ABBV    3.671835  3.723142  3.774448 -1.067619 -0.010320
           ABT     3.656643  3.682610  3.708576 -1.061455 -0.189850
...                     ...       ...       ...       ...       ...
2023-11-30 YUM     4.778174  4.828897  4.879620  0.199591  0.895190
           ZBH     4.623112  4.680042  4.736972 -0.254995  0.202355
           ZBRA    5.286738  5.345200  5.403662 -0.012923 -0.160356
           ZION    3.372132  3.515364  3.658596 -0.092737  0.696147
           ZTS     5.026941  5.115873  5.204804  0.963583  0.488186

[47458 rows x 9 columns]

  - Calculate 5-year rolling average of dollar volume for each stocks before filtering.

In [14]:
# data['dollar_volume'] = (data['dollar_volume'].unstack('ticker').rolling(5*12).mean().stack())

# data['dollar_vol_rank'] = (data.groupby('date')['dollar_volume'].rank(ascending=False))

# data = data[data['dollar_vol_rank']<150].drop(['dollar_volume', 'dollar_vol_rank'], axis=1)

data

                    adj close  garman_klass_vol        rsi    bb_low  \
date       ticker
2020-11-30 AAL      14.130000          0.044575  58.332321  2.440051
           AAPL    116.983955          0.000520  54.008276  4.698839
           ABBV     92.321564          0.100445  71.866669  4.373911
           ABT     102.758194          0.036883  48.977950  4.621924
           ACN     238.940903          0.032185  61.931833  5.376573
...                       ...               ...        ...       ...
2023-11-30 VRTX    356.839996         -0.015221  47.397467  5.843848
           VZ       36.730000         -0.009356  67.482270  3.547485
           WFC      42.790001          0.001316  59.733474  3.660538
           WMT     155.300003          0.001214  38.783824  5.054606
           XOM     104.500000          0.006574  45.335923  4.627209

                     bb_mid   bb_high       atr      macd
date       ticker
2020-11-30 AAL     2.613901  2.787751 -0.786781  0.861154
           AAPL    4.751182  4.803526  0.673168 -0.077952
           ABBV    4.471928  4.569946  0.049640  2.112392
           ABT     4.663147  4.704369  1.021236 -0.256771
           ACN     5.443973  5.511372  0.230954  1.248935
...                     ...       ...       ...       ...
2023-11-30 VRTX    5.905214  5.966581  1.628970 -0.687191
           VZ      3.594962  3.642439 -0.832373  1.943153
           WFC     3.729717  3.798896 -0.753369  0.773765
           WMT     5.101774  5.148942  0.981298 -0.649294
           XOM     4.660664  4.694120  0.645576 -1.352009

[5513 rows x 8 columns]

4. Calculate Monthly Returns for different time horizons as features.
   - To capture time series dynamics that reflect, for example, momentum patterns, we compute historical returns using the method .pct_change(lag), that is, returns over various monthly periods as identified by lags.

In [15]:
def calculate_returns(df):

  outlier_cutoff = 0.005

  lags = [1, 2, 3, 6, 9, 12]

  for lag in lags:
    df[f'return_{lag}m'] = (df['adj close']
                          .pct_change(lag)
                          .pipe(lambda x: x.clip(lower=x.quantile(outlier_cutoff),
                                                  upper=x.quantile(1-outlier_cutoff)))
                          .add(1)
                          .pow(1/lag)
                          .sub(1))
  return df

data = data.groupby(level=1, group_keys=False).apply(calculate_returns).dropna()

data

                    adj close  garman_klass_vol        rsi    bb_low  \
date       ticker
2021-11-30 AAL      17.690001         -0.009876  34.886438  2.916785
           AAPL    163.432648         -0.015856  68.678368  4.966191
           ABBV    106.648651          0.069558  52.881773  4.677108
           ABT     121.268394          0.043313  50.504815  4.791027
           ACN     347.075531          0.032054  51.087281  5.848531
...                       ...               ...        ...       ...
2023-11-30 VRTX    356.839996         -0.015221  47.397467  5.843848
           VZ       36.730000         -0.009356  67.482270  3.547485
           WFC      42.790001          0.001316  59.733474  3.660538
           WMT     155.300003          0.001214  38.783824  5.054606
           XOM     104.500000          0.006574  45.335923  4.627209

                     bb_mid   bb_high       atr      macd  return_1m  \
date       ticker
2021-11-30 AAL     3.044954  3.173123 -0.606922 -0.553927  -0.078646
           AAPL    5.034688  5.103185  0.852095  1.609841   0.105082
           ABBV    4.691887  4.706666 -0.408302  0.531626   0.005320
           ABT     4.817555  4.844084  0.866408  0.177622  -0.024207
           ACN     5.874897  5.901262  0.895457  0.525780  -0.003874
...                     ...       ...       ...       ...        ...
2023-11-30 VRTX    5.905214  5.966581  1.628970 -0.687191  -0.014554
           VZ      3.594962  3.642439 -0.832373  1.943153   0.045545
           WFC     3.729717  3.798896 -0.753369  0.773765   0.085529
           WMT     5.101774  5.148942  0.981298 -0.649294  -0.049630
           XOM     4.660664  4.694120  0.645576 -1.352009  -0.003726

                   return_2m  return_3m  return_6m  return_9m  return_12m
date       ticker
2021-11-30 AAL     -0.071514  -0.039124  -0.051146  -0.018566    0.018901
           AAPL     0.081620   0.029239   0.048739   0.035560    0.028256
           ABBV     0.040024  -0.011453   0.006915   0.011495    0.012094
           ABT      0.033821  -0.000302   0.013918   0.006702    0.013898
           ACN      0.058523   0.021237   0.041186   0.041120    0.031600
...                      ...        ...        ...        ...         ...
2023-11-30 VRTX     0.013000   0.008069   0.016446   0.023199    0.010074
           VZ       0.071004   0.023586   0.011612   0.000022    0.000952
           WFC      0.027896   0.014964   0.014919  -0.007139   -0.006896
           WMT     -0.014581  -0.015215   0.009942   0.011178    0.002830
           XOM     -0.052961  -0.017495   0.006642  -0.002726   -0.002317

[3581 rows x 14 columns]

5. Download Fama-French Factors and Calculate Rolling Factor Betas.
- We will introduce the Fama-French data to estimate the exposure of assets to common risk factors using linear regression.
- The five Fama-French factors, namely market risk, size, value, operating profitability, and investment have been shown empirically to explain asset returns and are commonly used to assess the risk/return profile of portfolios. Hence, it is natural to include past factor exposures as financial features in models.
- We can access the historical factor returns using the pandas-datareader and estimate historical exposures using the RollingOLS rolling linear regression.

In [32]:
# factor_data = web.DataReader('F-F_Research_Data_5_Factors_2x3',
#                               'famafrench',
#                               start='2010')[0].drop('RF', axis=1)
# factor_data.index = factor_data.index.to_timestamp()

# factor_data = factor_data.resample('M').last().div(100)

# factor_data.index.name = 'date'

# factor_data = factor_data.join(data['return_1m']).sort_index()

factor_data

                   Mkt-RF     SMB     HML     RMW     CMA  return_1m
date       ticker
2021-11-30 AAL    -0.0155 -0.0177 -0.0045  0.0720  0.0173  -0.078646
           AAPL   -0.0155 -0.0177 -0.0045  0.0720  0.0173   0.105082
           ABBV   -0.0155 -0.0177 -0.0045  0.0720  0.0173   0.005320
           ABT    -0.0155 -0.0177 -0.0045  0.0720  0.0173  -0.024207
           ACN    -0.0155 -0.0177 -0.0045  0.0720  0.0173  -0.003874
...                   ...     ...     ...     ...     ...        ...
2023-09-30 VRTX   -0.0524 -0.0179  0.0152  0.0187 -0.0082  -0.001722
           VZ     -0.0524 -0.0179  0.0152  0.0187 -0.0082  -0.073471
           WFC    -0.0524 -0.0179  0.0152  0.0187 -0.0082  -0.010414
           WMT    -0.0524 -0.0179  0.0152  0.0187 -0.0082  -0.016481
           XOM    -0.0524 -0.0179  0.0152  0.0187 -0.0082   0.057469

[3296 rows x 6 columns]

- Filter out stocks with less than 10 months of data.

In [33]:
factor_data.groupby(level=1).size()

ticker
AAL     23
AAPL    23
ABBV    23
ABT     23
ACN     23
        ..
WDC      8
WFC     23
WMT     23
WYNN    21
XOM     23
Length: 153, dtype: int64